version: '3.2'
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    restart: always
    ports:
      - 2181:2181

  app:
    build: .
    hostname: app
    links:
      - zookeeper
    depends_on:
      - zookeeper
